project:
  type: website
  output-dir: docs

website:
  title: "Proofbound"
  favicon: _resources/proofbound-logo-shield.svg
  navbar:
    logo: _resources/proofbound-logo-shield.svg
    left:
      - text: Home
        href: index.qmd
      - about.qmd

format:
  html:
    theme: 
      - minty
    css: styles.css
    toc: true

